"""
SMART-LM Report Generation Service
=====================================
Generates PDF (ReportLab) and DOCX (python-docx) inspection reports.
"""

import os
import logging
from datetime import datetime
from typing import Dict, Any, List, Optional

logger = logging.getLogger(__name__)

REPORTS_DIR = os.getenv(
    "SMARTLM_REPORTS_DIR",
    os.path.join(os.path.dirname(__file__), "..", "generated_reports"),
)
os.makedirs(REPORTS_DIR, exist_ok=True)

# Status colour mapping (for PDF)
STATUS_COLORS = {
    "VERIFIED_COMPLIANT": (0.18, 0.60, 0.34),      # green
    "POTENTIAL_VIOLATION": (0.80, 0.20, 0.20),      # red
    "NEEDS_HUMAN_REVIEW": (0.90, 0.60, 0.10),       # amber
}

SEVERITY_COLORS = {
    "HIGH": (0.80, 0.20, 0.20),
    "MEDIUM": (0.90, 0.60, 0.10),
    "LOW": (0.20, 0.60, 0.80),
}


# ---------------------------------------------------------------------------
# PDF Report
# ---------------------------------------------------------------------------

def generate_pdf(inspection_data: Dict[str, Any]) -> Optional[str]:
    """
    Generate a PDF report and return the file path.
    """
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib import colors
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import cm, mm
        from reportlab.platypus import (
            SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
            HRFlowable, Image as RLImage,
        )
        from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT

        iid = inspection_data["inspection_id"]
        filename = f"report_{iid}.pdf"
        filepath = os.path.join(REPORTS_DIR, filename)

        doc = SimpleDocTemplate(
            filepath,
            pagesize=A4,
            rightMargin=2 * cm,
            leftMargin=2 * cm,
            topMargin=2 * cm,
            bottomMargin=2 * cm,
        )

        styles = getSampleStyleSheet()
        story = []

        # ----- Header -----
        title_style = ParagraphStyle(
            "TitleStyle",
            parent=styles["Title"],
            fontSize=20,
            textColor=colors.HexColor("#0A1628"),
            spaceAfter=4,
            fontName="Helvetica-Bold",
        )
        sub_style = ParagraphStyle(
            "SubStyle",
            parent=styles["Normal"],
            fontSize=10,
            textColor=colors.HexColor("#4A5568"),
            spaceAfter=2,
        )
        story.append(Paragraph("SMART-LM", title_style))
        story.append(Paragraph("Smart Legal Metrology Compliance &amp; Inspection System", sub_style))
        story.append(Paragraph("Government Prototype — SIH 2026 | SIH26034", sub_style))
        story.append(HRFlowable(width="100%", thickness=2, color=colors.HexColor("#D4AF37")))
        story.append(Spacer(1, 0.3 * cm))

        # ----- Disclaimer -----
        disclaimer_style = ParagraphStyle(
            "Disclaimer",
            parent=styles["Normal"],
            fontSize=8,
            textColor=colors.HexColor("#718096"),
            backColor=colors.HexColor("#FFF8DC"),
            borderPadding=(4, 4, 4, 4),
            leading=12,
        )
        story.append(Paragraph(
            "⚠ PROTOTYPE — NOT FOR ENFORCEMENT: This report is generated by an automated inspection assistance "
            "system. Results are NOT a substitute for official legal enforcement decisions. All findings must be "
            "verified by a qualified Legal Metrology Inspector before any enforcement action.",
            disclaimer_style
        ))
        story.append(Spacer(1, 0.5 * cm))

        # ----- Inspection Info Table -----
        story.append(Paragraph("Inspection Details", styles["Heading2"]))
        overall_status = inspection_data.get("overall_status", "NEEDS_HUMAN_REVIEW")
        status_rgb = STATUS_COLORS.get(overall_status, (0.5, 0.5, 0.5))
        status_color = colors.Color(*status_rgb)

        info_data = [
            ["Inspection ID", inspection_data.get("inspection_id", "—")],
            ["Date & Time", str(inspection_data.get("created_at", datetime.now()))[:19]],
            ["Product Name", inspection_data.get("product_name", "Not detected")],
            ["Overall Status", overall_status.replace("_", " ")],
            ["Confidence", inspection_data.get("overall_confidence", "LOW")],
            ["Image Quality", inspection_data.get("image_quality", "—")],
        ]
        info_table = Table(info_data, colWidths=[5 * cm, 12 * cm])
        info_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#EDF2F7")),
            ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("ROWBACKGROUNDS", (0, 0), (-1, -1), [colors.white, colors.HexColor("#F7FAFC")]),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E0")),
            ("PADDING", (0, 0), (-1, -1), 5),
            ("TEXTCOLOR", (1, 3), (1, 3), status_color),
            ("FONTNAME", (1, 3), (1, 3), "Helvetica-Bold"),
        ]))
        story.append(info_table)
        story.append(Spacer(1, 0.5 * cm))

        # ----- Extracted Declarations -----
        story.append(Paragraph("Extracted Declarations", styles["Heading2"]))
        decl_data = [["Field", "Detected Value", "Confidence", "Status"]]
        declarations = inspection_data.get("declarations", [])
        for d in declarations:
            decl_data.append([
                d.get("field_name", "").replace("_", " ").title(),
                (d.get("extracted_value") or "Not detected")[:80],
                d.get("confidence", "LOW"),
                (d.get("status") or "—").replace("_", " "),
            ])

        if len(decl_data) > 1:
            decl_table = Table(decl_data, colWidths=[4 * cm, 8 * cm, 2.5 * cm, 3.5 * cm])
            decl_table.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0A1628")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 8),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F7FAFC")]),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E0")),
                ("PADDING", (0, 0), (-1, -1), 5),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ]))
            story.append(decl_table)
        else:
            story.append(Paragraph("No declarations extracted.", styles["Normal"]))

        story.append(Spacer(1, 0.5 * cm))

        # ----- Violations -----
        violations = inspection_data.get("violations", [])
        story.append(Paragraph(f"Findings &amp; Violations ({len(violations)})", styles["Heading2"]))
        if not violations:
            story.append(Paragraph("No violations or review items flagged.", styles["Normal"]))
        else:
            viol_data = [["Field", "Reason", "Severity", "Rule ID"]]
            for v in violations:
                reason_text = (v.get("reason") or "")[:120]
                viol_data.append([
                    (v.get("field_name") or "").replace("_", " ").title(),
                    reason_text,
                    v.get("severity", "MEDIUM"),
                    v.get("rule_id") or "—",
                ])
            viol_table = Table(viol_data, colWidths=[3 * cm, 9 * cm, 2.5 * cm, 3.5 * cm])
            viol_table.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#7B2D2D")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 8),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.HexColor("#FFF5F5"), colors.white]),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E0")),
                ("PADDING", (0, 0), (-1, -1), 5),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("WORDWRAP", (1, 1), (1, -1), True),
            ]))
            story.append(viol_table)

        story.append(Spacer(1, 0.5 * cm))

        # ----- Evidence Image -----
        image_path = inspection_data.get("image_path")
        if image_path and os.path.exists(image_path):
            story.append(Paragraph("Evidence Image", styles["Heading2"]))
            try:
                img = RLImage(image_path, width=10 * cm, height=7 * cm, kind="proportional")
                story.append(img)
            except Exception as ie:
                story.append(Paragraph(f"[Image could not be embedded: {ie}]", styles["Normal"]))

        story.append(Spacer(1, 0.5 * cm))

        # ----- Rule References -----
        story.append(Paragraph("Rule References", styles["Heading2"]))
        story.append(Paragraph(
            "Rules applied are prototype references based on the Legal Metrology "
            "(Packaged Commodities) Rules 2011 and amendments. All rules marked PROTOTYPE "
            "must be verified against current official Government of India Legal Metrology "
            "documents before enforcement use.",
            ParagraphStyle("RuleRef", parent=styles["Normal"], fontSize=8, textColor=colors.HexColor("#4A5568"))
        ))

        # ----- Footer note -----
        story.append(Spacer(1, 1 * cm))
        story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#CBD5E0")))
        story.append(Paragraph(
            f"Report generated: {datetime.now().strftime('%d %b %Y %H:%M')} | "
            "SMART-LM v1.0-prototype | SIH 2026",
            ParagraphStyle("Footer", parent=styles["Normal"], fontSize=7,
                           textColor=colors.HexColor("#A0AEC0"), alignment=TA_CENTER)
        ))

        doc.build(story)
        logger.info("PDF report generated: %s", filepath)
        return filepath

    except Exception as exc:
        logger.error("PDF generation failed: %s", exc)
        return None


# ---------------------------------------------------------------------------
# DOCX Report
# ---------------------------------------------------------------------------

def generate_docx(inspection_data: Dict[str, Any]) -> Optional[str]:
    """
    Generate an editable DOCX report and return the file path.
    """
    try:
        from docx import Document
        from docx.shared import Pt, RGBColor, Cm
        from docx.enum.text import WD_ALIGN_PARAGRAPH
        from docx.oxml.ns import qn
        from docx.oxml import OxmlElement

        iid = inspection_data["inspection_id"]
        filename = f"report_{iid}.docx"
        filepath = os.path.join(REPORTS_DIR, filename)

        doc = Document()

        # Page margins
        section = doc.sections[0]
        section.top_margin = Cm(2)
        section.bottom_margin = Cm(2)
        section.left_margin = Cm(2.5)
        section.right_margin = Cm(2.5)

        # Title
        title = doc.add_heading("SMART-LM", level=0)
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER
        sub = doc.add_paragraph("Smart Legal Metrology Compliance & Inspection System")
        sub.alignment = WD_ALIGN_PARAGRAPH.CENTER
        sub.runs[0].font.size = Pt(11)
        sub.runs[0].font.color.rgb = RGBColor(0x4A, 0x55, 0x68)

        doc.add_paragraph("Government Prototype — SIH 2026 | SIH26034").alignment = WD_ALIGN_PARAGRAPH.CENTER
        doc.add_paragraph()

        # Disclaimer
        disc = doc.add_paragraph(
            "⚠ PROTOTYPE — NOT FOR ENFORCEMENT: This report is generated by an automated "
            "inspection assistance system. Results are NOT a substitute for official legal "
            "enforcement decisions. All findings must be verified by a qualified Legal "
            "Metrology Inspector before any enforcement action."
        )
        disc.runs[0].font.size = Pt(9)
        disc.runs[0].font.color.rgb = RGBColor(0x71, 0x80, 0x96)

        # Inspection Details
        doc.add_heading("Inspection Details", level=1)
        overall_status = inspection_data.get("overall_status", "NEEDS_HUMAN_REVIEW")
        table = doc.add_table(rows=6, cols=2)
        table.style = "Table Grid"
        rows_data = [
            ("Inspection ID", inspection_data.get("inspection_id", "—")),
            ("Date & Time", str(inspection_data.get("created_at", datetime.now()))[:19]),
            ("Product Name", inspection_data.get("product_name") or "Not detected"),
            ("Overall Status", overall_status.replace("_", " ")),
            ("Confidence", inspection_data.get("overall_confidence", "LOW")),
            ("Image Quality", inspection_data.get("image_quality", "—")),
        ]
        for i, (label, val) in enumerate(rows_data):
            row = table.rows[i]
            row.cells[0].text = label
            row.cells[0].paragraphs[0].runs[0].bold = True
            row.cells[1].text = str(val)
        doc.add_paragraph()

        # Declarations
        doc.add_heading("Extracted Declarations", level=1)
        declarations = inspection_data.get("declarations", [])
        if declarations:
            dtable = doc.add_table(rows=1 + len(declarations), cols=4)
            dtable.style = "Table Grid"
            hdr = dtable.rows[0].cells
            hdr[0].text = "Field"
            hdr[1].text = "Detected Value"
            hdr[2].text = "Confidence"
            hdr[3].text = "Status"
            for cell in hdr:
                cell.paragraphs[0].runs[0].bold = True
            for i, d in enumerate(declarations):
                row = dtable.rows[i + 1].cells
                row[0].text = (d.get("field_name") or "").replace("_", " ").title()
                row[1].text = (d.get("extracted_value") or "Not detected")[:100]
                row[2].text = d.get("confidence") or "LOW"
                row[3].text = (d.get("status") or "—").replace("_", " ")
        else:
            doc.add_paragraph("No declarations extracted.")
        doc.add_paragraph()

        # Violations
        violations = inspection_data.get("violations", [])
        doc.add_heading(f"Findings & Violations ({len(violations)})", level=1)
        if not violations:
            doc.add_paragraph("No violations or review items flagged.")
        else:
            vtable = doc.add_table(rows=1 + len(violations), cols=4)
            vtable.style = "Table Grid"
            vhdr = vtable.rows[0].cells
            vhdr[0].text = "Field"
            vhdr[1].text = "Reason"
            vhdr[2].text = "Severity"
            vhdr[3].text = "Rule ID"
            for cell in vhdr:
                cell.paragraphs[0].runs[0].bold = True
            for i, v in enumerate(violations):
                row = vtable.rows[i + 1].cells
                row[0].text = (v.get("field_name") or "").replace("_", " ").title()
                row[1].text = (v.get("reason") or "")[:200]
                row[2].text = v.get("severity") or "MEDIUM"
                row[3].text = v.get("rule_id") or "—"
        doc.add_paragraph()

        # Rule Reference
        doc.add_heading("Rule References (Prototype)", level=1)
        doc.add_paragraph(
            "Rules applied are prototype references based on the Legal Metrology "
            "(Packaged Commodities) Rules 2011 and amendments. All rules marked PROTOTYPE "
            "must be verified against current official Government of India Legal Metrology "
            "documents before enforcement use."
        )

        # Inspector Review Section
        doc.add_heading("Inspector Review", level=1)
        doc.add_paragraph("Inspector Name: ___________________________________")
        doc.add_paragraph()
        doc.add_paragraph("Inspector Designation: ___________________________")
        doc.add_paragraph()
        doc.add_paragraph("Date of Physical Inspection: _____________________")
        doc.add_paragraph()
        doc.add_paragraph("Inspector Remarks:")
        doc.add_paragraph()
        doc.add_paragraph("_" * 80)
        doc.add_paragraph("_" * 80)
        doc.add_paragraph()
        doc.add_paragraph("Signature & Stamp: ___________________________________")

        doc.save(filepath)
        logger.info("DOCX report generated: %s", filepath)
        return filepath

    except Exception as exc:
        logger.error("DOCX generation failed: %s", exc)
        return None
